// Banco de dados das sementes
const seedsDatabase = [
    {
        id: 1,
        nomeVulgar: "Abiu",
        nomeCientifico: "Pouteria caimito",
        familia: "Sapotaceae",
        dataColeta: "24/08/2025",
        local: "Jundiaí",
        utilidades: {
            alimentação: "fruto de polpa doce, consumido in natura ou em sucos e sorvetes.",
            nutricional: "rico em vitaminas e minerais, fonte de energia.",
            "medicinal popular": "usado contra anemia, tosse e problemas respiratórios.",
            econômico: "cultivado em pomares e quintais para consumo e venda.",
        },
        image: "images/abiu.jpg",
    },
    {
        id: 2,
        nomeVulgar: "Fava-arara",
        nomeCientifico: "Parkia multijuga",
        familia: "Fabaceae",
        dataColeta: "23/07/2024",
        local: "Tucuruí",
        utilidades: {
            Aromatizante: "semente rica em cumarina, usada na perfumaria.",
            Medicinal: "tradicionalmente empregada contra tosses, gripes e bronquites.",
            Madeira: "muito densa e durável, usada em construções e móveis.",
            "Uso Cultural": "sementes utilizadas em artesanato e rituais tradicionais",
        },
        image: "images/fava_arara.jpg",
    },
    {
        id: 3,
        nomeVulgar: "Tento-vermelho",
        nomeCientifico: "Adenanthera pavonina",
        familia: "Fabaceae",
        dataColeta: "23/07/2024",
        local: "Tucuruí",
        utilidades: {
            Artesanato: "sementes vermelhas usadas em biojoias e enfeites.",
            Ornamental: "muito apreciado pela beleza e brilho das sementes.",
            Ecológico: "espécie nativa importante na recomposição florestal.",
        },
        image: "images/tento-vermelho.jpg",
        observacao: "semente tóxica, não comestível."
    },
    {
        id: 4,
        nomeVulgar: "Mututi",
        nomeCientifico: "Pternocarpus amazonicus",
        familia: "Fabaceae",
        dataColeta: "23/07/2024",
        local: "Tucuruí",
        utilidades: {
            madeira: "madeira nobre, utilizada em pisos, móveis de luxo e construção civil.",
            ornamental: "madeira de cor roxa intensa, muito valorizada no design.",
            resistência: "madeira pesada e durável, indicada para obras externas.",
            ecológico: "importante na recuperação de áreas degradadas.",
        },
        image: "images/mututi.jpg",
    },
    {
        id: 5,
        nomeVulgar: "Buriti",
        nomeCientifico: "Mauritia flexuosa",
        familia: "Arecaceae",
        dataColeta: "24/08/2025",
        local: "Santa Izabel-PA",
        utilidades: {
            alimentação: "polpa usada em sucos, doces, sorvetes e vinho.",
            cosmético: "óleo do fruto rico em vitamina A e carotenoides.",
            artesanal: "folhas e talos usados na confecção de peças artesanais (miriti).",
            ambiental: "espécie chave em áreas alagadas, ajuda na manutenção da fauna.",
        },
        image: "images/buriti.jpg",
    },
    {
        id: 6,
        nomeVulgar: "Castanha-do-Pará",
        nomeCientifico: "Bertholletia excelsa",
        familia: "Lecythidaceae",
        dataColeta: "24/08/2025",
        local: "Santa Izabel do Pará",
        utilidades: {
            alimentação: "amêndoa comestível, rica em óleos e selênio.",
            cosmético: "óleo utilizado na indústria de cosméticos e fármacos.",
            ecológico: "alimento essencial para a fauna amazônica (cutias, araras).",
            econômico: "produto extrativista de grande importância na Amazônia.",
        },
        image: "images/castanha-para.jpg",
    },
    {
        id: 7,
        nomeVulgar: "Jutaí-café (Jatobá)",
        nomeCientifico: "Hymenaea courbaril",
        familia: "Fabaceae",
        dataColeta: "23/07/2024",
        local: "Tucuruí",
        utilidades: {
            alimentacao: "polpa farinácea adocicada, nutritiva.",
            madeira: "extremamente dura e resistente, usada em construções pesadas e pisos.",
            medicinal: "partes da planta utilizadas tradicionalmente contra problemas respiratórios e inflamações.",
            econômico: "fruto aproveitado na culinária regional (farinha, bebidas).",
            ecológico: "importante para a fauna, frutos consumidos por animais.",
        },
        image: "images/jatoba.jpg",
    },
    {
        id: 8,
        nomeVulgar: "Tachi-branco",
        nomeCientifico: "Tachigali alba",
        familia: "Fabaceae",
        dataColeta: "23/07/2024",
        local: "Tucuruí",
        utilidades: {
            madeira: "leve, usada em construção temporária, caixotaria e movelaria simples.",
            ambiental: "espécie pioneira, útil em reflorestamentos.",
            ecológico: "sementes aladas dispersas pelo vento auxiliam na regeneração natural.",
            ornamental: "porte elegante, presença em projetos paisagísticos.",
        },
        image: "images/tachi-branco.jpg",
    },
    {
        id: 9,
        nomeVulgar: "Ipê-rosa",
        nomeCientifico: "Handroanthus impetiginosus",
        familia: "Bignoniaceae",
        dataColeta: "23/07/2024",
        local: "Tucuruí",
        utilidades: {
            madeira: "muito resistente, usada em construção pesada e mobiliário.",
            ornamental: "árvore de floração exuberante, bastante cultivada em praças e avenidas.",
            "medicinal popular": "casca usada em chás (pau-d’arco) para fins anti-inflamatórios e imunoestimulantes.",
            ecológico: "flores atraem polinizadores, especialmente abelhas.",
        },
        image: "images/ipe-rosa.jpg",
    },
    {
        id: 10,
        nomeVulgar: "Sapucaia",
        nomeCientifico: "Lecythis pisonis",
        familia: "Lecythidaceae",
        dataColeta: "23/07/2024",
        local: "Tucuruí",
        utilidades: {
            alimentação: "sementes oleaginosas, comestíveis (semelhantes à castanha).",
            madeira: "dura e resistente, usada em construções e móveis.",
            ornamental: "árvore de grande porte e valor paisagístico.",
            ecológico: "frutos servem de alimento para fauna.",
        },
        image: "images/sapucaia.jpg",
    },
    {
        id: 11,
        nomeVulgar: "Tamanqueira",
        nomeCientifico: "Aegiphila sellowiana",
        familia: "Lamiaceae",
        dataColeta: "23/07/2024",
        local: "Tucuruí – PA",
        utilidades: {
            madeira: "resistente, usada tradicionalmente para fazer tamancos.",
            ornamental: "árvore útil em paisagismo urbano e rural.",
            ecológico: "aplicável em recuperação de áreas degradadas.",
        },
        image: "images/tamanqueira.jpg",
    },
    {
        id: 12,
        nomeVulgar: "Sucupira",
        nomeCientifico: "Pterodon emarginatus Vogel",
        familia: "Fabaceae",
        dataColeta: "23/07/2024",
        local: "Tucuruí – PA",
        utilidades: {
            medicinal: "óleo da semente com propriedades anti-inflamatórias, usado para tratar artrite, reumatismo e dores.",
            cosmético: "presente em produtos naturais terapêuticos.",
            madeira: "resistente, usada em construções e móveis.",
            artesanal: "sementes aproveitadas em biojoias e enfeites.",
        },
        image: "images/sucupira.jpg",
    },
    {
        id: 13,
        nomeVulgar: "Maranhoto",
        nomeCientifico: "Colubrina glandulosa",
        familia: "Rhamnaceae",
        dataColeta: "23/07/2024",
        local: "Tucuruí – PA",
        utilidades: {
            medicinal: "flavonoides com ação anti-inflamatória e antioxidante.",
            apícola: "atrativa para abelhas (produção de mel).",
            ecológico: "usada em projetos de reflorestamento e recuperação ambiental.",
            artesanal: "sementes com potencial decorativo.",
        },
        image: "images/maranhoto.jpg",
    },
    {
        id: 14,
        nomeVulgar: "Mirindiba-doce",
        nomeCientifico: "Glycydendron amazonicum",
        familia: "Euphorbiaceae",
        dataColeta: "23/07/2024",
        local: "Tucuruí – PA",
        utilidades: {
            madeira: "muito dura, usada em construções, móveis, lenha e carvão vegetal.",
            medicinal: "folhas utilizadas na medicina tradicional como chá.",
            ambiental: "boa para reflorestamento e atração de fauna.",
            ornamental: "aplicável em arborização.",
        },
        image: "images/mirindiba.jpg",
    },
    {
        id: 15,
        nomeVulgar: "Açaí",
        nomeCientifico: "Euterpe oleracea",
        familia: "Arecaceae",
        dataColeta: "24/08/2025",
        local: "Jundiaí – PA",
        utilidades: {
            alimentação: "polpa usada em sucos, “açaí na tigela”, doces, geleias e licores.",
            cosmético: "óleo da semente usado em cremes e shampoo.",
            artesanal: "sementes (caroços) transformadas em biojoias e objetos decorativos.",
            construção: "estipe utilizado em construções rústicas, palha para cobertura.",
            medicinal: "propriedades antioxidantes e anti-inflamatórias identificadas em estudos.",
        },
        image: "images/acai.jpg",
    },
    {
        id: 16,
        nomeVulgar: "Andiroba",
        nomeCientifico: "Carapa guianensis",
        familia: "Meliaceae",
        dataColeta: "21/08/2025",
        local: "Distrito de Americano – PA",
        utilidades: {
            medicinal: "usado contra dores musculares, artrite, inflamações e como cicatrizante.",
            cosmético: "presente em sabonetes, cremes, shampoos e loções.",
            repelente: "eficaz contra insetos, principalmente mosquitos.",
            artesanal: "óleo também pode ser usado na confecção de velas repelentes.",
        },
        image: "images/andiroba.jpg",
    },
    {
        id: 17,
        nomeVulgar: "Uxi",
        nomeCientifico: "Endopleura uchi",
        familia: "Humiriaceae",
        dataColeta: "25/08/2025",
        local: "Distrito de Americano – PA",
        utilidades: {
            fitoterápico: "tradicionalmente usado no tratamento de problemas uterinos (miomas, inflamações, hemorragias).",
            "antimicrobiano e Anti-Inflamatório": "usado contra infecções urinárias, inflamações e distúrbios ginecológicos.",
            antioxidante: "contém bergenina, substância de interesse farmacêutico.",
            "uso Popular": "preparado em chás ou extratos para fortalecer o sistema imunológico.",
        },
        image: "images/uxi.jpg",
    },
    {
        id: 18,
        nomeVulgar: "Jambeiro",
        nomeCientifico: "Syzygium malaccense L.",
        familia: "Myrtaceae",
        dataColeta: "21/08/2025",
        local: "Distrito de Americano – PA",
        utilidades: {
            "Medicinal Popular": "em algumas regiões, é utilizada em forma de chá ou maceração como auxiliar no tratamento de diabetes, ajudando no controle da glicemia.",
            Adstringente: "devido à presença de taninos, pode ser usada para auxiliar em problemas gastrointestinais leves, como diarreias.",
            Cicatrização: "a semente triturada é usada em preparos caseiros para aplicação em feridas superficiais.",
        },
        image: "images/jambeiro.jpg",
    },
    {
        id: 19,
        nomeVulgar: "Ingá",
        nomeCientifico: "Inga edulis",
        familia: "Fabaceae",
        dataColeta: "24/08/2025",
        local: "Jundiaí – PA",
        utilidades: {
            "produção de Mudas": "usado em reflorestamento por recuperar solos e fixar nitrogênio.",
            "alimentação Animal": "pode ser usado na alimentação animal após cozimento.",
            "potencial Alimentício": "possui amido e proteína, com potencial para consumo humano.",
            "extração óleo": "seu óleo pode ser utilizado em cosméticos e como fonte de energia.",
        },
        image: "images/inga.jpg",
    },
    {
        id: 20,
        nomeVulgar: "Breu sucuruba",
        nomeCientifico: "Trattinnickia burserifolia Mart.",
        familia: "Burseraceae",
        dataColeta: "23/07/2024",
        local: "Tucuruí",
        utilidades: {
            "Óleo vegetal": "Da semente pode ser extraído um óleo rico em ácidos graxos, que pode ter uso em cosméticos, sabonetes artesanais e até como potencial biocombustível.",
            "Alimentação animal": "Em algumas comunidades amazônicas, as sementes são aproveitadas em pequenas quantidades na ração de animais, após secagem.",
            "Reflorestamento e recuperação de áreas degradadas": "As sementes são fundamentais para a reprodução da espécie, que é importante na restauração florestal pela boa adaptação em solos amazônicos."
        },
        image: "images/breu_sucuruba.jpg"
    },
    {
        id: 21,
        nomeVulgar: "Arapari-do-brejo",
        nomeCientifico: "Macrolobium acaciifolium",
        familia: "Fabaceae",
        dataColeta: "23/07/2024",
        local: "Tucuruí",
        utilidades: {
            "Artesanato": "Colares, pulseiras e outros objetos decorativos.",
            "Uso cultural": "Aplicações culturais diversas.",
            "Ecologia": "Planta nativa usada em reflorestamento e preservação ambiental.",
            "Toxicidade": "Sementes tóxicas se ingeridas, uso apenas externo."
        },
        image: "images/arapari_do_brejo.jpg"
    },
    {
        id: 22,
        nomeVulgar: "Cumarú",
        nomeCientifico: "Dipteryx odorata",
        familia: "Fabaceae",
        dataColeta: "26/08/2025",
        local: "Castanhal",
        utilidades: {
            alimentação: "As sementes secas e raladas são usadas como especiaria em confeitaria e bebidas, especialmente na Europa e em alta gastronomia, sorvetes, chocolates, bolos e licores.",
            madeira: "Alta densidade e durabilidade, possuindo resistência a agentes xilófagos.",
            ornamental: "Árvore de grande porte, sendo bastante utilizada em jardins e recuperação paisagística.",
            ecológico: "O fruto serve de alimento para a fauna local, que fornece alimentos para roedores."
        },
        image: "images/cumaru.jpg"
    },
    {
        id: 23,
        nomeVulgar: "Acapú",
        nomeCientifico: "Vouacapoua americana",
        familia: "Fabaceae",
        dataColeta: "26/08/2025",
        local: "Castanhal",
        utilidades: {
            alimentação: "Não tem uso alimentício.",
            madeira: "Extremamente dura ao corte, possuindo resistência à compressão e aos agentes xilófagos, acarretando na sua alta durabilidade.",
            ornamental: "Árvore de grande porte, usada para arborização em parques e jardins extensos.",
            econômico: "Madeira bastante utilizada no mercado interno e externo, sendo usada para construções de pisos, estacas e pontes.",
            ecológico: "Seus frutos servem de alimento para roedores, aves e pequenos mamíferos."
        },
        image: "images/acapu.jpg"
    },
    {
        id: 24,
        nomeVulgar: "Ipê branco",
        nomeCientifico: "Tabebuia roseo-alba",
        familia: "Bignoniaceae",
        dataColeta: "23/07/2024",
        local: "Tucuruí",
        utilidades: {
            alimentação: "Não é usado na alimentação. Diferente de outras árvores nativas, ele não produz frutos ou sementes comestíveis.",
            madeira: "É pesada, resistente e durável, podendo ser empregada em construções, móveis e acabamentos.",
            ornamental: "Utilizada em praças, avenidas e jardins, por seu espetáculo de floração.",
            econômico: "Seu valor econômico é tanto pelo uso direto de sua madeira e função ornamental, quanto pelos benefícios indiretos relacionados ao turismo e à preservação ambiental.",
            ecológico: "Suas flores atraem abelhas, contribuindo para a polinização."
        },
        image: "images/ipe-branco.jpg"
    },
    {
        id: 25,
        nomeVulgar: "Cedro",
        nomeCientifico: "Cedrela fissilis",
        familia: "Meliaceae",
        dataColeta: "23/07/2024",
        local: "Tucuruí",
        utilidades: {
            alimentação: "O cedro não é usado na alimentação humana nem animal.",
            madeira: "Moderada — resiste relativamente bem a fungos e cupins.",
            ornamental: "O cedro é valorizado como árvore de sombra e destaque paisagístico em áreas amplas.",
            econômico: "O cedro tem altíssimo valor econômico, principalmente pela madeira nobre e aromática, amplamente usada em marcenaria fina e exportação.",
            ecológico: "É uma espécie de grande importância para a floresta, pois fornece sombra, abrigo, recursos para polinizadores e proteção ambiental."
        },
        image: "images/cedro.jpg"
    },
    {
        id: 26,
        nomeVulgar: "Bacuripiri",
        nomeCientifico: "Platonia insigs",
        familia: "Clusiaceae",
        dataColeta: "",
        local: "",
        utilidades: {
            alimentação: "O fruto possui polpa suculenta, sendo usada no preparo de suco, sorvetes, geleias.",
            madeira: "Não é tão conhecida quanto os frutos, mas possui densidade média e boa resistência.",
            ornamental: "Pode ser utilizada em projetos de arborização ecológica, unindo o aspecto ornamental com a recuperação do solo.",
            econômico: "Tem valores econômicos principalmente pelo uso dos frutos na alimentação e processamentos derivados.",
            ecológico: "Atrai fauna e favorece a regeneração natural, contribuindo para projetos de restauração ecológica."
        },
        image: "images/bacuripiri.jpg"
    },
]
